### ISSUE TITLE
relax is absolutely weird

### ISSUE THREAD

**Issue by GodOfCircles** [mrflashstudio/osu-rx#19]
slow maps are working fine but if i'm trying to play 7 stars it's missing more than myself without cheats. Please fix this issue. Thanks in advance!

**Comment by mrflashstudio** [comment]
This tells me absolutely nothing. Are you using MPGH build?

**Comment by mrflashstudio** [comment]
Pretty much every hitscan weirdness (if that's what you mean and if you're using MPGH build) has been fixed by fddb492f70718e2cc6002cb89e11cb4893ddd38a, 696a55f9af9a89ccc3ec99616cb7bf977722f065, e72d6464e622604e18a896b3d561fa55f7a8addb, 2247bc1be001cfd14964f7ecf397fba336dd7cec and 0ce5704cbbf630e773b60c2c6187a53e0a8c8bf3. Reopen if you can provide any additional info. Thanks.
